FROM node:16-alpine

# change for runtime reload code

USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

# Step 2: Download and install dependency
COPY --chown=node:node ./package.json/ ./
RUN npm install
COPY --chown=node:node ./ ./

# Step 3: Tell the image what to do when it starts as container
CMD ["npm","run","start"]